from pathlib import Path
import secrets

# Server
p=Path('server/server.js'); s=p.read_text()
s=s.replace("const http = require('http');\n", "const http = require('http');\nconst crypto = require('crypto');\n")
s=s.replace("function randomPseudo() {\n", "function reconnectToken() { return crypto.randomBytes(24).toString('hex'); }\nfunction playerId() { return crypto.randomUUID ? crypto.randomUUID() : crypto.randomBytes(16).toString('hex'); }\nfunction randomPseudo() {\n")
s=s.replace("players: room.players.map(p => ({ id: p.id, pseudo: p.pseudo, ready: p.ready, host: p.id === room.hostId, connected: p.connected !== false }))", "players: room.players.map(p => ({ id: p.id, playerId: p.playerId, pseudo: p.pseudo, ready: p.ready, host: p.id === room.hostId, connected: p.connected !== false }))")
s=s.replace("socketId: p.id,\n    pseudo: p.pseudo,", "socketId: p.id,\n    playerId: p.playerId,\n    pseudo: p.pseudo,")
s=s.replace("players: [{ id: socket.id, pseudo, ready: false, connected: true }]", "players: [{ id: socket.id, playerId: playerId(), reconnectToken: reconnectToken(), pseudo, ready: false, connected: true }]")
s=s.replace("ack({ ok: true, room: publicRoom(room) });\n    emitRoom(room);\n  });\n\n  socket.on('joinRoom'", "ack({ ok: true, room: publicRoom(room), resume: { code, pseudo, playerId: room.players[0].playerId, token: room.players[0].reconnectToken } });\n    emitRoom(room);\n  });\n\n  socket.on('joinRoom'",1)
s=s.replace("room.players.push({ id: socket.id, pseudo, ready: false, connected: true });", "const joined = { id: socket.id, playerId: playerId(), reconnectToken: reconnectToken(), pseudo, ready: false, connected: true };\n    room.players.push(joined);")
needle="ack({ ok: true, room: publicRoom(room) });\n    emitRoom(room);\n  });\n\n  socket.on('setReady'"
s=s.replace(needle,"ack({ ok: true, room: publicRoom(room), resume: { code, pseudo: joined.pseudo, playerId: joined.playerId, token: joined.reconnectToken } });\n    emitRoom(room);\n  });\n\n  socket.on('resumeRoom', (payload = {}, ack = () => {}) => {\n    const code = cleanCode(payload.code), pid = cleanText(payload.playerId, 80), token = cleanText(payload.token, 120);\n    const room = rooms.get(code);\n    if (!room || !room.launched || !room.game) return ack({ ok:false, error:'Cette partie en cours n’est plus disponible.' });\n    const lobbyPlayer = room.players.find(p => p.playerId === pid && p.reconnectToken === token);\n    if (!lobbyPlayer) return ack({ ok:false, error:'Impossible de vérifier votre place dans cette partie.' });\n    leaveCurrentRoom(socket);\n    const oldSocketId=lobbyPlayer.id; lobbyPlayer.id=socket.id; lobbyPlayer.connected=true;\n    if (room.hostId===oldSocketId) room.hostId=socket.id;\n    const gp=room.game.players.find(p=>!p.bot&&p.playerId===pid);\n    if(!gp) return ack({ok:false,error:'Siège de jeu introuvable.'});\n    gp.socketId=socket.id;gp.connected=true;socket.join(code);socket.data.roomCode=code;\n    const resume={code,pseudo:lobbyPlayer.pseudo,playerId:pid,token:lobbyPlayer.reconnectToken};\n    ack({ok:true,room:publicRoom(room),game:publicGameView(room,socket.id),resume});emitRoom(room);emitGame(room);\n  });\n\n  socket.on('setReady'",1)
p.write_text(s)

# Client
p=Path('index.html'); s=p.read_text()
s=s.replace("<div class=\"onlineActions\"><button id=\"onlineJoinRoom\" class=\"onlinePrimary\">Rejoindre</button><button class=\"onlineBack\" data-online-back>← Retour</button></div>", "<div class=\"onlineActions\"><button id=\"onlineJoinRoom\" class=\"onlinePrimary\">Rejoindre</button><button id=\"onlineResumeRoom\" class=\"onlineSecondary hidden\">Partie en cours</button><button class=\"onlineBack\" data-online-back>← Retour</button></div><div id=\"onlineResumeHint\" class=\"onlineStatus hidden\"></div>")
s=s.replace("let onlineSelectedMode=null,onlineReadyState=false,onlineSocket=null,onlineRoom=null,onlineGameState=null,onlineSetupSelectedRegions=[],onlineSetupDraft={color:null,portrait:null};", "let onlineSelectedMode=null,onlineReadyState=false,onlineSocket=null,onlineRoom=null,onlineGameState=null,onlineSetupSelectedRegions=[],onlineSetupDraft={color:null,portrait:null};\nconst ONLINE_RESUME_KEY='tribuOnlineResumeV1';\nfunction onlineResumeRead(){try{const v=JSON.parse(localStorage.getItem(ONLINE_RESUME_KEY)||'null');return v&&v.code&&v.playerId&&v.token?v:null}catch(_){return null}}\nfunction onlineResumeSave(v){if(!v)return;localStorage.setItem(ONLINE_RESUME_KEY,JSON.stringify(v));onlineResumeRefresh()}\nfunction onlineResumeClear(){localStorage.removeItem(ONLINE_RESUME_KEY);onlineResumeRefresh()}\nfunction onlineResumeRefresh(){const v=onlineResumeRead(),b=$('onlineResumeRoom'),h=$('onlineResumeHint');if(!b||!h)return;b.classList.toggle('hidden',!v);h.classList.toggle('hidden',!v);if(v){b.textContent='Partie en cours';h.textContent=(v.pseudo||'Joueur')+' · '+v.code}}")
s=s.replace("$('onlineJoin').onclick=()=>{onlinePseudo();showOnlineScreen('onlineJoinScreen')};", "$('onlineJoin').onclick=()=>{onlinePseudo();onlineResumeRefresh();showOnlineScreen('onlineJoinScreen')};")
s=s.replace("const res=await onlineAck('createRoom',{pseudo:onlinePseudo(),name:$('onlineRoomName').value,code:$('onlineRoomCode').value,mode:onlineSelectedMode,maxHumans:onlineSeatCount(onlineSelectedMode),bots:onlineBotCount(onlineSelectedMode),victoryPoints:+$('onlineVictory').value});renderOnlineLobby(res.room)", "const res=await onlineAck('createRoom',{pseudo:onlinePseudo(),name:$('onlineRoomName').value,code:$('onlineRoomCode').value,mode:onlineSelectedMode,maxHumans:onlineSeatCount(onlineSelectedMode),bots:onlineBotCount(onlineSelectedMode),victoryPoints:+$('onlineVictory').value});onlineResumeSave(res.resume);renderOnlineLobby(res.room)")
s=s.replace("const res=await onlineAck('joinRoom',{code,pseudo:onlinePseudo()});renderOnlineLobby(res.room)", "const res=await onlineAck('joinRoom',{code,pseudo:onlinePseudo()});onlineResumeSave(res.resume);renderOnlineLobby(res.room)")
needle="$('onlineLaunch').onclick=async()=>{try{await onlineAck('launchGame',{})}catch(e){onlineError(e)}};"
s=s.replace(needle, "$('onlineResumeRoom').onclick=async()=>{const saved=onlineResumeRead();if(!saved)return onlineResumeRefresh();try{const res=await onlineAck('resumeRoom',saved);onlineResumeSave(res.resume);onlineRoom=res.room;onlineSelectedMode=res.room.mode;$('victoryMode').value=String(res.room.victoryPoints||3);applyOnlineGameState(res.game)}catch(e){onlineResumeClear();onlineError(e)}};\n"+needle+"\nonlineResumeRefresh();")
p.write_text(s)
