const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const os=require('node:os');
const {createPublicActivity,projectPublicState}=require('../public-activity');
function fixture(){return {activityId:'12345678-1234-1234-1234-123456789abc',startedAt:1000,name:'Partie',mode:'2v3',victoryPoints:3,launched:true,players:[{playerId:'p',connected:true,reconnectToken:'SECRET_TOKEN'}],game:{status:'playing',players:[{playerId:'p'}]},legacySnapshot:{
 g:{active:0,turn:2,phase:'play',seed:'SECRET_SEED',online:{secret:'SECRET_ONLINE'},players:[{name:'Alice',hand:['SECRET_HAND'],seenCards:['SECRET_SPY'],inPlay:[8,19],faction:0,gold:5}],b:{A1:{owner:0,units:3,private:'SECRET_BOARD',building:{type:'Forteresse',owner:0,private:'SECRET_BUILDING'}}},sea:{U:{fleets:{0:2},private:'SECRET_SEA'}},deck:['SECRET_DECK'],oracleDeck:[3,2],oracleActive:0,log:['SECRET_LOG'],discard:[1]},
 rule:{agentModalState:{private:'SECRET_AGENT'},commerceDeals:['SECRET_DEAL'],divinationState:{private:'SECRET_ORACLE'},gameOverState:null,battle:{attacker:0,defender:null,target:'A1',stack:[{cardId:1,owner:0,secret:'SECRET_STACK'}]}},
 public:{scores:[2],attackPower:5,defensePower:6,secret:'SECRET_FACTS'}
 }}}
test('public projector exposes only selected public fields',()=>{const room=fixture(),before=JSON.stringify(room),result=projectPublicState(room);assert(!JSON.stringify(result).includes('SECRET'));assert.equal(JSON.stringify(room),before);assert.equal(result.players[0].handCount,1);assert.equal(result.players[0].score,2);assert.equal(result.oracleNext,null);assert.equal(result.battle.attackPower,5);assert.equal(result.board.A1.units,3);assert(!('code' in result));assert(!('seed' in result));assert(!('hand' in result.players[0]));});
test('history survives module restart and records one result per game',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'tribu-history-test-')),file=path.join(dir,'history.json'),room=fixture();let clock=2000;const service=createPublicActivity({file,now:()=>clock});service.update(room);assert.equal(service.history().length,0);room.legacySnapshot.rule.gameOverState={winner:0,points:3};clock=9000;service.update(room);service.update(room);assert.equal(service.history().length,1);const restored=createPublicActivity({file});restored.update(room);assert.equal(restored.history().length,1);assert.equal(restored.history()[0].durationSeconds,8);assert(!fs.readFileSync(file,'utf8').includes('SECRET'));});
test('malformed optional legacy fields cannot expose arbitrary nested objects',()=>{const room=fixture();room.legacySnapshot.g.players=[null];room.legacySnapshot.rule={};assert.doesNotThrow(()=>projectPublicState(room));});
test('failed history writes remain visible as unavailable',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'tribu-history-fail-'));const file=path.join(dir,'block');fs.writeFileSync(file,'x');const service=createPublicActivity({file:path.join(file,'history.json'),logger:{error(){}}}),room=fixture();room.legacySnapshot.rule.gameOverState={winner:0};service.update(room);assert.equal(service.list(new Map([[1,room]])).historyAvailable,false);});
test('the live public journal remains available but completed results contain no archived journal',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'tribu-journal-')),file=path.join(dir,'history.json'),room=fixture();room.legacySnapshot.public.journal=Array.from({length:245},(_,i)=>'Événement '+i);room.legacySnapshot.rule.gameOverState={winner:0};const service=createPublicActivity({file});assert.equal(service.update(room).journal.length,245);const list=service.list(new Map([[1,room]]));assert(!('hasJournal' in list.recent[0]));assert(!('journal' in list.recent[0]));const restored=createPublicActivity({file});assert(!('journal' in restored.history()[0]));assert.equal(restored.history()[0].winner,0);assert(!JSON.stringify(restored.history()).includes('SECRET'));});

