from pathlib import Path

server=Path('server/server.js')
s=server.read_text()
old="""function publicRoom(room) {\n  return {\n"""
new="""function tokenHash(value){return crypto.createHash('sha256').update(String(value||'')).digest('hex')}\nfunction roomRecoveryCapsule(room){\n  if(!room||!room.launched||!room.game||room.game.status!=='playing')return null;\n  const game=JSON.parse(JSON.stringify(room.game));\n  (game.players||[]).forEach(p=>{if(!p.bot){p.socketId=null;p.connected=false}});\n  return {version:1,code:room.code,name:room.name,mode:room.mode,maxHumans:room.maxHumans,bots:room.bots,victoryPoints:room.victoryPoints,seed:room.seed,hostPlayerId:room.hostPlayerId||((room.players.find(p=>p.id===room.hostId)||{}).playerId)||null,players:room.players.map(p=>({playerId:p.playerId,pseudo:p.pseudo,ready:!!p.ready,tokenHash:p.reconnectTokenHash||tokenHash(p.reconnectToken)})),game,legacyMode:!!room.legacyMode,legacyRevision:room.legacyRevision||0,legacySnapshot:room.legacySnapshot||null};\n}\nfunction restoreRoomFromRecovery(saved){\n  const cap=saved&&saved.recovery,code=cleanCode(saved&&saved.code),pid=cleanText(saved&&saved.playerId,80),token=cleanText(saved&&saved.token,120);\n  if(!cap||cap.version!==1||cleanCode(cap.code)!==code||!cap.game||cap.game.status!=='playing'||!Array.isArray(cap.players))return null;\n  const seat=cap.players.find(p=>p.playerId===pid&&p.tokenHash===tokenHash(token));if(!seat)return null;\n  const room={code,name:cleanText(cap.name,30)||`Partie ${code}`,mode:cleanText(cap.mode,20),maxHumans:Math.max(2,Math.min(5,Number(cap.maxHumans)||2)),bots:Math.max(0,Math.min(4,Number(cap.bots)||0)),victoryPoints:[3,4,5].includes(Number(cap.victoryPoints))?Number(cap.victoryPoints):3,hostId:null,hostPlayerId:cleanText(cap.hostPlayerId,80)||null,launched:true,seed:Number(cap.seed)>>>0,game:cap.game,legacyMode:!!cap.legacyMode,legacyRevision:Math.max(0,Number(cap.legacyRevision)||0),legacySnapshot:cap.legacySnapshot||null,players:cap.players.map(p=>({id:null,playerId:cleanText(p.playerId,80),reconnectToken:null,reconnectTokenHash:String(p.tokenHash||''),pseudo:cleanText(p.pseudo,24),ready:!!p.ready,connected:false}))};\n  (room.game.players||[]).forEach(p=>{if(!p.bot){p.socketId=null;p.connected=false}});\n  rooms.set(code,room);return room;\n}\nfunction publicRoom(room) {\n  return {\n"""
assert old in s
s=s.replace(old,new,1)
s=s.replace("host: p.id === room.hostId, connected: p.connected !== false","host: room.hostPlayerId ? p.playerId===room.hostPlayerId : p.id === room.hostId, connected: p.connected !== false",1)
s=s.replace("hostId: socket.id,\n      launched: false,","hostId: socket.id,\n      hostPlayerId: null,\n      launched: false,",1)
s=s.replace("rooms.set(code, room);\n    socket.join(code);","room.hostPlayerId=room.players[0].playerId;\n    rooms.set(code, room);\n    socket.join(code);",1)
old="""  socket.on('resumeRoom', (payload = {}, ack = () => {}) => {\n    const code = cleanCode(payload.code), pid = cleanText(payload.playerId, 80), token = cleanText(payload.token, 120);\n    const room = rooms.get(code);\n    if (!room || !room.launched || !room.game) return ack({ ok:false, error:'Cette partie en cours n’est plus disponible.' });\n    const lobbyPlayer = room.players.find(p => p.playerId === pid && p.reconnectToken === token);\n"""
new="""  socket.on('resumeRoom', (payload = {}, ack = () => {}) => {\n    const code = cleanCode(payload.code), pid = cleanText(payload.playerId, 80), token = cleanText(payload.token, 120);\n    let room = rooms.get(code);\n    if (!room) room=restoreRoomFromRecovery(payload);\n    if (!room || !room.launched || !room.game) return ack({ ok:false, error:'Cette partie en cours n’est plus disponible.' });\n    const lobbyPlayer = room.players.find(p => p.playerId === pid && (p.reconnectToken === token || p.reconnectTokenHash === tokenHash(token)));\n"""
assert old in s
s=s.replace(old,new,1)
s=s.replace("const oldSocketId=lobbyPlayer.id; lobbyPlayer.id=socket.id; lobbyPlayer.connected=true;\n    if (room.hostId===oldSocketId) room.hostId=socket.id;","const oldSocketId=lobbyPlayer.id; lobbyPlayer.id=socket.id; lobbyPlayer.connected=true;lobbyPlayer.reconnectToken=token;lobbyPlayer.reconnectTokenHash=tokenHash(token);\n    if (room.hostId===oldSocketId || room.hostPlayerId===pid) room.hostId=socket.id;",1)
s=s.replace("ack({ok:true,room:publicRoom(room),game:publicGameView(room,socket.id),resume});emitRoom(room);emitGame(room);","ack({ok:true,room:publicRoom(room),game:publicGameView(room,socket.id),resume:{...resume,recovery:roomRecoveryCapsule(room)}});emitRoom(room);emitGame(room);",1)
s=s.replace("ack({ok:true,revision:room.legacyRevision||0,youIndex,bootstrap:legacyBootstrapView(room,socket.id),snapshot:room.legacySnapshot||null});","ack({ok:true,revision:room.legacyRevision||0,youIndex,bootstrap:legacyBootstrapView(room,socket.id),snapshot:room.legacySnapshot||null,recovery:roomRecoveryCapsule(room)});",1)
s=s.replace("socket.emit('legacyState',{snapshot:room.legacySnapshot,revision:room.legacyRevision||0,youIndex:legacyYouIndex(room,p.id)});","socket.emit('legacyState',{snapshot:room.legacySnapshot,revision:room.legacyRevision||0,youIndex:legacyYouIndex(room,p.id),recovery:roomRecoveryCapsule(room)});",1)
s=s.replace("ack({ok:true,revision:room.legacyRevision});emitLegacy(room,socket.id);","ack({ok:true,revision:room.legacyRevision,recovery:roomRecoveryCapsule(room)});emitLegacy(room,socket.id);",1)
server.write_text(s)

index=Path('index.html')
h=index.read_text()
h=h.replace("function onlineResumeSave(v){if(!v)return;localStorage.setItem(ONLINE_RESUME_KEY,JSON.stringify(v));onlineResumeRefresh()}","function onlineResumeSave(v){if(!v)return;const prev=onlineResumeRead()||{};localStorage.setItem(ONLINE_RESUME_KEY,JSON.stringify({...prev,...v,recovery:v.recovery||prev.recovery||null}));onlineResumeRefresh()}\nfunction onlineResumeSaveRecovery(recovery){if(!recovery)return;const prev=onlineResumeRead();if(!prev)return;onlineResumeSave({...prev,recovery})}",1)
h=h.replace("socket.on('legacyState',packet=>onlineLegacyApply(packet));","socket.on('legacyState',packet=>{onlineResumeSaveRecovery(packet&&packet.recovery);onlineLegacyApply(packet)});",1)
h=h.replace("function onlineAck(action,payload){return connectOnline().then(socket=>new Promise((resolve,reject)=>socket.emit(action,payload,res=>{if(res&&res.ok){resolve(res);return}","function onlineAck(action,payload){return connectOnline().then(socket=>new Promise((resolve,reject)=>socket.emit(action,payload,res=>{if(res&&res.ok){if(res.recovery)onlineResumeSaveRecovery(res.recovery);resolve(res);return}",1)
h=h.replace("$('onlineResumeRoom').onclick=async()=>{const saved=onlineResumeRead();if(!saved)return onlineResumeRefresh();try{const res=await onlineAck('resumeRoom',saved);onlineResumeSave(res.resume);onlineRoom=res.room;onlineSelectedMode=res.room.mode;$('victoryMode').value=String(res.room.victoryPoints||3);applyOnlineGameState(res.game)}catch(e){onlineResumeClear();onlineError(e)}};","$('onlineResumeRoom').onclick=async()=>{const saved=onlineResumeRead();if(!saved)return onlineResumeRefresh();try{const res=await onlineAck('resumeRoom',saved);onlineResumeSave(res.resume);onlineRoom=res.room;onlineSelectedMode=res.room.mode;$('victoryMode').value=String(res.room.victoryPoints||3);applyOnlineGameState(res.game)}catch(e){onlineError(e)}};",1)
index.write_text(h)
