from pathlib import Path
p=Path('index.html')
s=p.read_text()
repls=[]
repls.append(("main{display:grid;grid-template-columns:210px minmax(0,780px) 320px;", "main{display:grid;grid-template-columns:100px minmax(0,780px) 320px;"))
repls.append(("@media(max-width:900px){main{grid-template-columns:76px minmax(0,1fr)}.rightRail{grid-column:2;position:static;max-height:none}.playerCard{font-size:11px}.playerHandSummary{white-space:normal;flex-direction:column;gap:1px}.bottomZone", "@media(max-width:900px){main{grid-template-columns:76px minmax(0,1fr)}.rightRail{grid-column:2;position:static;max-height:none}.playerCard{font-size:11px}.bottomZone"))
repls.append((".playerRail{position:sticky;top:10px;display:flex;flex-direction:column;gap:5px;z-index:50}\n.playerHandSummary{background:#19201d;border:3px solid #777;border-radius:9px;padding:5px 6px;display:flex;align-items:center;justify-content:space-between;gap:5px;font-size:9px;font-weight:900;white-space:nowrap}\n", ".playerRail{position:sticky;top:10px;display:flex;flex-direction:column;gap:5px;z-index:50}\n"))
repls.append((".bottomPanel{background:#19201d;border-radius:9px;padding:10px;min-width:0}.bottomPanel h3{margin:0 0 7px}\n", ".bottomPanel{background:#19201d;border-radius:9px;padding:10px;min-width:0}.bottomPanel h3{margin:0 0 7px}\n.compactHandTitle{display:flex;align-items:center;gap:16px;flex-wrap:wrap}\n.compactHandTitle .handStat{font-size:13px;font-weight:900}\n"))
repls.append(("      <span id=\"handCount\" class=\"hidden\">0</span>\n      <div id=\"hand\" class=\"handHorizontal\"></div>", "      <h3 class=\"compactHandTitle\" id=\"handSummaryTitle\"><span>Main — <span id=\"handCount\">0</span> carte(s)</span><span class=\"handStat\" id=\"handGold\">Or : 0</span><span class=\"handStat\" id=\"handUnits\">Unités : 0/0</span></h3>\n      <div id=\"hand\" class=\"handHorizontal\"></div>"))
repls.append((" const viewer=localViewer();\n if(Number.isInteger(viewer)&&G.players[viewer]){\n   const pl=G.players[viewer],summary=document.createElement('div');\n   summary.className='playerHandSummary';summary.style.borderColor=COLORS[viewer];summary.style.color=COLORS[viewer];\n   summary.innerHTML='<span>Main - '+pl.hand.length+' carte(s)</span><span>Or : '+pl.gold+'</span><span>Unités : '+totalUnits(viewer)+'/'+cap(viewer)+'</span>';\n   rail.appendChild(summary);\n }\n renderInPlay(viewer);", " const viewer=localViewer();\n renderInPlay(viewer);"))
repls.append((" const handPlayer=displayedHandViewer();\n const h=$('hand');h.innerHTML='';", " const handPlayer=displayedHandViewer();\n const handTitle=$('handSummaryTitle'),handGold=$('handGold'),handUnits=$('handUnits');\n if(handTitle)handTitle.style.color=handPlayer!==null?COLORS[handPlayer]:'';\n if(handGold)handGold.textContent=handPlayer!==null?'Or : '+p(handPlayer).gold:'Or : —';\n if(handUnits)handUnits.textContent=handPlayer!==null?'Unités : '+totalUnits(handPlayer)+'/'+cap(handPlayer):'Unités : —';\n const h=$('hand');h.innerHTML='';"))
# Terminal Agent results must not remain a serialized priority lock.
repls.append((" openAgentModal('Espion — carte observée','Vous avez vu dans la main de <b>'+p(target).name+'</b> :<br><br><b>'+CARDS[id].name+'</b><br>'+CARDS[id].effect);\n log(p(actor).name+' utilise un Espion sur '+p(target).name+'.');\n render();", " openAgentModal('Espion — carte observée','Vous avez vu dans la main de <b>'+p(target).name+'</b> :<br><br><b>'+CARDS[id].name+'</b><br>'+CARDS[id].effect);\n agentModalState=null;\n log(p(actor).name+' utilise un Espion sur '+p(target).name+'.');\n render();"))
repls.append(("   openAgentModal('Voleur — '+n,'Échec critique : le Voleur est défaussé.');\n   render();return;", "   openAgentModal('Voleur — '+n,'Échec critique : le Voleur est défaussé.');\n   agentModalState=null;render();return;"))
repls.append(("   openAgentModal('Voleur — '+n,'Rien ne se passe.');\n   render();return;", "   openAgentModal('Voleur — '+n,'Rien ne se passe.');\n   agentModalState=null;render();return;"))
repls.append((" openAgentModal('Voleur — réussite','Vous volez <b>'+CARDS[id].name+'</b> à '+p(target).name+'.');\n log(p(actor).name+' vole une carte dans la main de '+p(target).name+'.');render();", " openAgentModal('Voleur — réussite','Vous volez <b>'+CARDS[id].name+'</b> à '+p(target).name+'.');\n agentModalState=null;\n log(p(actor).name+' vole une carte dans la main de '+p(target).name+'.');render();"))
repls.append((" openAgentModal('Voleur — réussite','Vous volez <b>'+CARDS[id].name+'</b> en jeu à '+p(target).name+'.');\n log(p(actor).name+' vole '+CARDS[id].name+' en jeu à '+p(target).name+'.');render();", " openAgentModal('Voleur — réussite','Vous volez <b>'+CARDS[id].name+'</b> en jeu à '+p(target).name+'.');\n agentModalState=null;\n log(p(actor).name+' vole '+CARDS[id].name+' en jeu à '+p(target).name+'.');render();"))
repls.append((" openAgentModal('Voleur — vol précis','Vous volez directement <b>'+CARDS[id].name+'</b> à '+p(target).name+'.');\n log(p(actor).name+' utilise Voleur pour prendre une carte repérée par Espion chez '+p(target).name+'.');render();", " openAgentModal('Voleur — vol précis','Vous volez directement <b>'+CARDS[id].name+'</b> à '+p(target).name+'.');\n agentModalState=null;\n log(p(actor).name+' utilise Voleur pour prendre une carte repérée par Espion chez '+p(target).name+'.');render();"))
for old,new in repls:
    if old not in s:
        raise SystemExit('Missing expected block:\n'+old[:220])
    s=s.replace(old,new,1)
p.write_text(s)
