from pathlib import Path
p=Path('index.html')
s=p.read_text(encoding='utf-8')

def rep(old,new,label):
    global s
    if old not in s:
        raise SystemExit(f'MISSING {label}')
    s=s.replace(old,new,1)

rep("function audioPlaySfx(name,vol=.8){\n if(!audioSfxEnabled||!AUDIO_SRC[name])return;\n const a=new Audio(AUDIO_SRC[name]);a.volume=vol;const p=a.play();if(p&&p.catch)p.catch(()=>{});\n}","""let onlineSfxSeq=0,onlineSfxEvents=[],onlineSfxSeenSeq=0;\nfunction audioPlaySfx(name,vol=.8){\n if(!audioSfxEnabled||!AUDIO_SRC[name])return;\n if(G&&G.online&&G.online.legacySync&&!onlineLegacyApplying){\n   const ev={seq:++onlineSfxSeq,name,vol};\n   onlineSfxEvents.push(ev);if(onlineSfxEvents.length>24)onlineSfxEvents=onlineSfxEvents.slice(-24);\n   onlineSfxSeenSeq=ev.seq;\n }\n const a=new Audio(AUDIO_SRC[name]);a.volume=vol;const p=a.play();if(p&&p.catch)p.catch(()=>{});\n}\nfunction onlinePlaySyncedSfx(events,seq){\n if(!Array.isArray(events)){onlineSfxSeenSeq=Math.max(onlineSfxSeenSeq,Number(seq)||0);return}\n events.filter(e=>e&&Number(e.seq)>onlineSfxSeenSeq).sort((a,b)=>a.seq-b.seq).forEach(e=>{\n   onlineSfxSeenSeq=Math.max(onlineSfxSeenSeq,Number(e.seq)||0);\n   audioPlaySfx(e.name,Number.isFinite(Number(e.vol))?Number(e.vol):.8);\n });\n onlineSfxSeenSeq=Math.max(onlineSfxSeenSeq,Number(seq)||0);\n}\n""","audio sync")

rep("let onlineLegacyRevision=0,onlineLegacyApplying=false,onlineLegacyLastDigest='',onlineLegacyPushTimer=null,onlineLegacyBotDriverIndex=null,onlineLegacyBattleViewSeconds=null,onlineLegacyGoldViewSeconds=null;","let onlineLegacyRevision=0,onlineLegacyApplying=false,onlineLegacyLastDigest='',onlineLegacyPushTimer=null,onlineLegacyBotDriverIndex=null,onlineLegacyBattleViewSeconds=null,onlineLegacyGoldViewSeconds=null,onlineLegacyGoldTickRender=false;","gold tick flag")

rep("""   goldReaction.seconds--;\n   if(goldReaction.seconds<=0){resolveGoldGain();return}\n   render();""","""   goldReaction.seconds--;\n   if(goldReaction.seconds<=0){resolveGoldGain();return}\n   onlineLegacyGoldTickRender=!!(G&&G.online&&G.online.legacySync);\n   render();\n   onlineLegacyGoldTickRender=false;""","gold tick no push")

rep(""" goldReaction={receiver,amount,source,after,seconds:10,turnOwner:G.active,turnEpoch};\n log(p(receiver).name+' doit recevoir '+amount+' Or : '+(isHotseatMode()?'réactions hot-seat sans chrono.':'fenêtre de réaction de 10 secondes.'));""",""" const pausedBattle=!!battle;\n if(pausedBattle){clearInterval(battleTick);clearTimeout(botReactionTimer)}\n goldReaction={receiver,amount,source,after,seconds:10,turnOwner:G.active,turnEpoch,pausedBattle};\n log(p(receiver).name+' doit recevoir '+amount+' Or : '+(isHotseatMode()?'réactions hot-seat sans chrono.':'fenêtre de réaction de 10 secondes.')+(pausedBattle?' La bataille est mise en pause.':''));""","pause battle on gold")

rep("""   turnOwner:r.turnOwner!==undefined?r.turnOwner:G.active,\n   turnEpoch:r.turnEpoch!==undefined?r.turnEpoch:turnEpoch\n };""","""   turnOwner:r.turnOwner!==undefined?r.turnOwner:G.active,\n   turnEpoch:r.turnEpoch!==undefined?r.turnEpoch:turnEpoch,\n   pausedBattle:!!r.pausedBattle\n };""","ambush preserve battle pause")

rep(""" G.players[r.receiver].gold+=r.amount;\n audioPlaySfx('gold',.78);\n log(p(r.receiver).name+' reçoit finalement '+r.amount+' Or'+(r.source?' ('+r.source+')':'')+'.');\n if(triggerRichDragon(r.receiver,r.after))return;\n if(r.after==='beginPlay')beginPlay();else render();""",""" G.players[r.receiver].gold+=r.amount;\n audioPlaySfx('gold',.78);\n log(p(r.receiver).name+' reçoit finalement '+r.amount+' Or'+(r.source?' ('+r.source+')':'')+'.');\n if(r.pausedBattle&&battle)battle.seconds=15;\n if(triggerRichDragon(r.receiver,r.after))return;\n if(r.pausedBattle&&battle){\n   resumeBattleTimer();\n   log('Gain d’Or résolu : la bataille reprend avec 15 secondes.');\n }\n if(r.after==='beginPlay')beginPlay();else render();""","resume battle after gold")

rep("""function onlineLegacyResumeBattleView(){\n clearInterval(battleTick);clearTimeout(botReactionTimer);\n if(!battle){onlineLegacyBattleViewSeconds=null;hideBattle();return;}\n showBattle();renderBattle();""","""function onlineLegacyResumeBattleView(){\n clearInterval(battleTick);clearTimeout(botReactionTimer);\n if(!battle){onlineLegacyBattleViewSeconds=null;hideBattle();return;}\n showBattle();renderBattle();\n if(goldReaction&&goldReaction.pausedBattle){\n   onlineLegacyBattleViewSeconds=null;\n   const pt=$('priorityTimer');if(pt)pt.textContent='En pause — gain d’Or';\n   return;\n }""","remote battle stays paused")

rep("""   oraclePendingNormalMap,turnEpoch,divinationState,recruitSnapshot,gameOverState,commerceDeals,commerceSeq,\n   onlineBotDriverIndex:onlineLegacyBotDriverIndex""","""   oraclePendingNormalMap,turnEpoch,divinationState,recruitSnapshot,gameOverState,commerceDeals,commerceSeq,\n   onlineSfxSeq,onlineSfxEvents,\n   onlineBotDriverIndex:onlineLegacyBotDriverIndex""","snapshot sfx")

rep(""" divinationState=null;recruitSnapshot=null;gameOverState=null;commerceDeals=[];commerceSeq=1;onlineLegacyBotDriverIndex=null;""",""" divinationState=null;recruitSnapshot=null;gameOverState=null;commerceDeals=[];commerceSeq=1;onlineLegacyBotDriverIndex=null;\n onlineSfxSeq=0;onlineSfxEvents=[];onlineSfxSeenSeq=0;""","bootstrap sfx")

rep(""" recruitSnapshot=r.recruitSnapshot||null;gameOverState=r.gameOverState||null;commerceDeals=r.commerceDeals||[];commerceSeq=r.commerceSeq||1;onlineLegacyBotDriverIndex=Number.isInteger(r.onlineBotDriverIndex)?r.onlineBotDriverIndex:null;\n onlineLegacyRevision=packet.revision||0;dest=null;picks={};""",""" recruitSnapshot=r.recruitSnapshot||null;gameOverState=r.gameOverState||null;commerceDeals=r.commerceDeals||[];commerceSeq=r.commerceSeq||1;onlineLegacyBotDriverIndex=Number.isInteger(r.onlineBotDriverIndex)?r.onlineBotDriverIndex:null;\n onlineSfxSeq=Number(r.onlineSfxSeq)||0;onlineSfxEvents=Array.isArray(r.onlineSfxEvents)?r.onlineSfxEvents:[];\n onlineLegacyRevision=packet.revision||0;dest=null;picks={};""","apply sfx state")

rep(""" onlineLegacyLastDigest=onlineLegacyDigest();render();onlineLegacyLastDigest=onlineLegacyDigest();onlineLegacyApplying=false;onlineLegacyLockControls();\n onlineLegacyResumeBattleView();""",""" const incomingSfx=onlineSfxEvents.slice(),incomingSfxSeq=onlineSfxSeq;\n onlineLegacyLastDigest=onlineLegacyDigest();render();onlineLegacyLastDigest=onlineLegacyDigest();onlineLegacyApplying=false;onlineLegacyLockControls();\n onlineLegacyApplying=true;onlinePlaySyncedSfx(incomingSfx,incomingSfxSeq);onlineLegacyApplying=false;\n onlineLegacyResumeBattleView();""","play remote sfx")

rep(""" if(G&&G.online&&G.online.legacySync){\n   onlineLegacyLockControls();\n   if(G.players&&G.players[G.active]&&!G.players[G.active].bot)onlineLegacyBotDriverIndex=null;\n   onlineLegacyMaybePush();\n }""",""" if(G&&G.online&&G.online.legacySync){\n   onlineLegacyLockControls();\n   if(G.players&&G.players[G.active]&&!G.players[G.active].bot)onlineLegacyBotDriverIndex=null;\n   if(!onlineLegacyGoldTickRender)onlineLegacyMaybePush();\n }""","suppress gold tick commits")

rep("""   if(o.name==='Givre mortel'){\n     destroySeaUnits('U','Givre mortel');\n     if(prev==='Canicule'){log('Givre mortel est sans effet après Canicule.');finishOracleResolution();render();completeOracleResolution();return}\n     beginOracleSacrifices('e','Givre mortel','Icenia, la cité blanche');return;\n   }""","""   if(o.name==='Givre mortel'){\n     if(prev==='Canicule'){log('Givre mortel est sans effet après Canicule.');finishOracleResolution();render();completeOracleResolution();return}\n     destroySeaUnits('U','Givre mortel');\n     beginOracleSacrifices('e','Givre mortel','Icenia, la cité blanche');return;\n   }""","givre after canicule")

p.write_text(s,encoding='utf-8')
